name: 'Create GitHub Issue'
description: 'Create a GitHub issue from a workflow run'
author: 'Me'

inputs:
  title:
    description: 'The title of the issue'
    required: true
  body:
    description: 'The body of the issue'
    required: true
  token:
    description: 'The GitHub token to use'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
  