name: AWS Auth 
run-name: AWS Auth
permissions: 
  contents: read 
  id-token: write
on:
  workflow_call:
    secrets:
      oidc-role: 
        required: true 
        description: ARN of the OIDC Role to Assume
jobs:
  account-auth:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        id: auth
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: ${{ secrets.AWS_SESSION_NAME }}
      - name: Check ID 
        run: aws sts get-caller-identity --query "Account" --output text
      - name: ECR Login
        id: login
        uses: aws-actions/amazon-ecr-login@v1
        with: 
          registries: 