name: Test

on:
    pull_request:
        types: [opened]
    push:
        branches:
            - main
            - dev

jobs:
    test:
        runs-on: ubuntu-latest
        env:
            artifact: tfplan
        steps:
            - uses: actions/checkout@v3
            - run: ls -la
            - uses: ./
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  artifact: ${{ env.artifact }}