name: Test

on:
    pull_request:
        types: [opened]
    push:
        branches:
            - main
            - dev

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./
              with:
                  title: 'Test Issue'
                  body: 'This is a test issue'
                  token: ${{ secrets.GITHUB_TOKEN }}